### ISSUE TITLE
Add ParserFunctions Extension to Wiki

### ISSUE THREAD

**Issue by Teksura** [danielcsims/Free-Sprite-Haven#9]
https://www.mediawiki.org/wiki/Extension:ParserFunctions

https://meta.wikimedia.org/wiki/Help:Calculation

I'm working on templates to auto-generate dice pools based on the aspect and information pulled from the page. One of the things I'd like it to do is automatically add the connection as pulled from the page to the dicepools displayed by the template. However, this requires an extension.  There are also a number of other obnoxiously useful things I noticed in ParserFunctions which I'd really like to make use of.

**Comment by danielcsims** [comment]
Installed https://www.shadowhaven.info/Special:Version
